### PR TITLE
nixd/lspserver: fix high cpu on fd polling

### LINKED ISSUE #627: high cpu load on hangup/close of the file descriptor
**Describe the bug**
If for some reason the input file descriptor was closed or hung up the poll function (https://github.com/nix-community/nixd/blob/main/nixd/lspserver/src/Connection.cpp#L154) will return and will set POLLHUP or POLLNVAL.
This happens on every call to poll.
This is not catched inside the for loop which will result in high cpu load till nixd is closed.

**Logs (Required)**

strace output:
```
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000) = 1 ([{fd=8, revents=POLLHUP}])
kill(162650, 0)                         = 0
poll([{fd=8, events=POLLIN|POLLPRI}], 1, 1000^C) = 1 ([{fd=8, revents=POLLHUP}])
strace: Process 162681 detached
```

**Configuration**
1. run `echo test | nixd`

**Expected behavior**
nixd exits after fd is closed.

**Additional context**
My current problem comes from neovim.
It seems that neovim does close the fd sometimes.

### PR DESCRIPTION
**Pull request by jduepmeier**
Fixes #627

### CODE REVIEW

**Review by inclyc — APPROVED** [review]
LGTM, thanks! 

Don't know why the CI is failing. But I don't think it is caused by your commit.

**Comment by jduepmeier** [comment]
looks like it tries to compile with llvm-18 and not llvm-16 (as defined in the flake)

**Comment by inclyc** [comment]
> looks like it tries to compile with llvm-18 and not llvm-16 (as defined in the flake)

Yes I think that's the problem. However I didn't push any commit before your PR, and previously it was correct, don't know why meson uses llvm-18.

**Comment by inclyc** [comment]
I think it is caused by [the upgrading to ubuntu 24.04](https://github.com/actions/runner-images/issues/10636) by github. So I fixed the runner version tag, and rebased your branch.

**Comment by inclyc** [comment]
Wait, this commit triggers CI error after merged:

[regression/nixd TIMEOUT        60.16s   killed by signal 15 SIGTERM](https://github.com/nix-community/nixd/actions/runs/12459165593)

**Pull request merged**
