### PR TITLE
nixd/documentLinkProvider: conform closer to spec

### PR DESCRIPTION
**Pull request by happysalada**
Submitting a PR with the suggested fix. Testing right now.

Fixes: #187

### CODE REVIEW

**Comment by happysalada** [comment]
alright, I just tested this and it works.
trying a few gotodefinitions, I get some errors though.
```
nixd err <- "I[09:04:21.630] 38386: <-- reply(5)\n"
2023-07-01T09:04:21.631 helix_lsp::transport [ERROR] nixd err <- "I[09:04:21.631] 38386: --> reply:textDocument/definition(3)\n"
2023-07-01T09:04:21.631 helix_view::editor [ERROR] editor error: Async job failed: data did not match any variant of untagged enum GotoDefinitionResponse
```
(I tried on an import keyword)

trying on a module in a flake for exemple I get
```
 reply:nixd/ipc/textDocument/definition(17) requested expression is not an ExprVar., error: 3\n"
2023-07-01T09:07:04.709 helix_lsp::transport [ERROR] nixd err <- "I[09:07:04.708] 38386: <-- reply(15)\n"
2023-07-01T09:07:04.710 helix_lsp::transport [ERROR] nixd err <- "I[09:07:04.709] 38386: <-- reply(17)\n"
2023-07-01T09:07:04.710 helix_lsp::transport [ERROR] nixd err <- "I[09:07:04.710] 38386: <-- reply(16)\n"
2023-07-01T09:07:04.712 helix_lsp::transport [ERROR] nixd err <- "I[09:07:04.711] 38386: --> reply:textDocument/definition(5)\n"
2023-07-01T09:07:04.712 helix_view::editor [ERROR] editor error: Async job failed: data did not match any variant of untagged enum GotoDefinitionResponse
```

Just making sure that those are expected.

**Comment by inclyc** [comment]
The regression tests should be updated for this change:

https://github.com/nix-community/nixd/blob/2cb95feae01f8b27557c44d80c95c2134cab9ca9/nixd/tools/nixd/test/initialize.md?plain=1#L38

**Comment by happysalada** [comment]
meson test gave me
```
No such build data file as '/Users/raphael/dev/nixd/meson-private/build.dat'.
```

**Comment by inclyc** [comment]
> meson test gave me
> 
> ```
> No such build data file as '/Users/raphael/dev/nixd/meson-private/build.dat'.
> ```


```
meson test -C <the-directory-you-configured>
```

**Review by inclyc — APPROVED** [review]

**Pull request merged**
