### PR TITLE
docs/editor-setup: add the doc

### PR DESCRIPTION
**Pull request by inclyc**
Fixes: #100

### CODE REVIEW

**Comment by ncfavier** [comment]
Could you please add instructions for Vim/Neovim?

**Comment by inclyc** [comment]
> Could you please add instructions for Vim/Neovim?

I'm not using vim/neovim :)

I do think adding such document will be very nice! However, thanks to my friend @Ruixi-rebirth who added official nvim-lspconfig upstream support for nixd: https://github.com/neovim/nvim-lspconfig/pull/2644.

If you have such things working on your editor, I will be very glad to accept & merge the PR, see https://github.com/nix-community/nixd/blob/db818511c22da2a898f8075f6e1d74e15d960fb0/docs/editor-setup.md?plain=1#L1-L3

**Comment by inclyc** [comment]
You might want to see: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.txt#nixd

**Comment by ncfavier** [comment]
That seems perfect, thanks. I think the doc should mention that for Neovim, and more generally explain that `nixd` is an LSP server, so should work out of the box with any LSP client if you just set `nixd` as the server command.

**Comment by inclyc** [comment]
> I think the doc should mention that for Neovim.

Oh thanks, I already prepared a PR which cherry-picks the documentation for nvim from previously closed #54  (so I explicitly set the author to @Ruixi-rebirth ). 

> and more generally explain that nixd is an LSP server, so should work out of the box with any LSP client if you just set nixd as the server command.

❤️

**Pull request merged**
